#Hadley's Presentation from November 2016
The purpose of this project is to code each of the eight examples from Hadley's November 2016 talk at the NYC Datavis meetup: [https://speakerdeck.com/hadley/eight-visualisation-challenges-with-ggplot2](https://speakerdeck.com/hadley/eight-visualisation-challenges-with-ggplot2)

```{r, echo=FALSE}
library("ggplot2")
```

## Challenge 1: Labelling Plots

New labelling layers are:  
Title  
Subtitle  
Caption  

```{r echo=FALSE}
ggplot(mpg, aes(displ, hwy))+
  geom_point(aes(color = class))+
  geom_smooth(se = FALSE, method = "loess")+
  labs(
    title = "Title: Fuel efficiency generally decreases with engine size",
    subtitle = "Subtitle: Two seaters (sports cars) are an exception because of their light weight",
    caption = "Caption: Data from fueleconomy.gov"
  )
```


## Challenge 2: Secondary Axis

New function "sec.axis"  
Only 1-to-1 transformations are allowed

```{r echo=FALSE}
ggplot (mpg, aes(displ, hwy)) +
  geom_point() +
  scale_y_continuous(
    "mpg",
    sec.axis = sec_axis(
      ~ 235 / .,
      name = "1/100 km",
      breaks=seq(2,20, by = 2)
    )
  )
```
